source = "test:test@(127.0.0.1:3306)/test"
dest = "test:test@(127.0.0.1:3306)/test_1"
# tables: table to check schema,default is all.eg :["order_*","goods"]
tables = []
# tables_ignore: table to ignore check schema,default is Null :["order_*","goods"]
tables_ignore = []

[alter_ignore]

  [alter_ignore."tb1*"]
  column = [
    "aaa",
    "a*"
  ]
  index = [
    "aa"
  ]
  foreign = []

[overwrite_data]
# overwrite tables data
tables = ["tongbi_robot_lv", "safe_box"]

[email]
send_mail = false
smtp_host = "smtp.163.com:25"
from = "xxx@163.com"
password = "xxx"
to = "xxx@163.com"